version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: NetCore
deploy:
- provider: NuGet
  api_key:
    secure: 7p/a33OEvB9wM70NOXJnC1UIbBzJ2TkQAo9AZnR/1bEg3iWyCbuDVyvmct2uyCD7
  artifact: /.*\.nupkg/